export const data = [
  {
    id: 1,
    name: "HVD Essential",
    url: "hvd-essential",
    image: "/packages/pack1.webp",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol",
      "Thyroid profile: TSH",
      "Kidney profile: Urea, Creatinine",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria,Others",
    ],
    price: "1299",
    cancelled: "2400",
  },
  {
    id: 2,
    name: "HVD Advance",
    url: "hvd-advance",
    image: "/packages/pack2.webp",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid profile: TSH, FT3, FT4",
      "Kidney prole: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells, RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
    ],
    price: "2399",
    cancelled: "4400",
  },
  {
    id: 3,
    name: "HVD Platinum",
    url: "hvd-platinum",
    image: "/packages/pack6.png",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid profile: TSH, FT3, FT4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
    ],
    price: "3999",
    cancelled: "7000",
  },
  {
    id: 4,
    name: "HVD EXCLUSIVE (MALE)",
    url: "hvd-exclusive-male",
    image: "/packages/pack11.jpg",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid profile: TSH, FT3, FT4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Prostate Specic Antigen: Total PSA, Free PSA",
      "Iron profile: Serum Iron, UIBC-Serum, TIBC, Transferrin Saturation",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
    ],
    price: "5499",
    cancelled: "8500",
  },
  {
    id: 5,
    name: "HVD EXCLUSIVE (FEMALE)",
    url: "hvd-exclusive-female",
    image: "/packages/pack9.png",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid profile: TSH, FT3, FT4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Iron Profile: Serum Iron, UIBC-Serum, TIBC, Transferrin Saturation",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
    ],
    price: "4499",
    cancelled: "7000",
  },
  {
    id: 6,
    name: "HVD AYUSHMAN",
    url: "hvd-ayushman",
    image: "/packages/pack12.png",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes profile- HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid Prole: - TSH, T3, T4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
      "Ultrasound Whole Abdomen",
      "Chest X Ray",
      "ECG",
    ],
    price: "5499",
    cancelled: "10000",
  },
  {
    id: 7,
    name: "HVD COMPREHENSIVE ( SENIOR CITIZEN MALE)",
    url: "hvd-comprehensive-senior-citizen-male",
    image: "/packages/pack7.png",
    description: [
      "Complete Blood Count: - Hemoglobin, TLC, DLC, RBC Count, PCV, MCV, MCH, MCHC, Platelet Count, RDW",
      "Diabetes Prole: - HbA1c, Fasting Glucose, Estimated Average Glucose",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid Prole: - TSH, T3, T4",
      "Kidney Prole: - Urea, Creatinine, Uric Acid, Bun, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Prostate Specic Antigen:-Total PSA, Free PSA",
      "Iron Prole: - Serum Iron, UIBC- Serum, TIBC, Transferrin saturation",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
      "Ultrasound Whole Abdomen",
      "Chest X Ray",
      "ECG",
    ],
    price: "6999",
    cancelled: "12000",
  },
  {
    id: 8,
    name: "HVD COMPREHENSIVE ( SENIOR CITIZEN FEMALE)",
    url: "hvd-comprehensive-senior-citizen-female",
    image: "/packages/pack5.webp",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes Prole: - HbA1c, Fasting Glucose, Estimated Average Glucose ",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid Prole: - TSH, T3, T4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "Bone health: Calcium, Phosphorus, Vitamin D",
      "Nervous System: Vitamin B12",
      "Iron Profile: Serum Iron, UIBC-Serum, TIBC, Transferrin Saturation",
      "Urine R/M: Colour, Transparency, Specic gravity, pH, Albumin, Sugar, Pus cells,RBC, Casts, Crystals, Epithelial cells, Bacteria, Others",
      "Ultra Sound Whole Abdomen",
      "Chest X Ray",
      "E.C.G.",
    ],
    price: "5999",
    cancelled: "10000",
  },
  {
    id: 9,
    name: "HVD CARDIAC HEALTH PACKAGE",
    url: "hvd-cardiac",
    image: "/packages/pack3.webp",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Diabetes Prole: - HbA1c, Fasting Glucose, Estimated Average Glucose ",
      "Lipid profile: Triglycerides, Total Cholesterol, HDL, LDL, VLDL, Total/HDL, LDL/HDL ratio",
      "Thyroid Prole: - TSH, T3, T4",
      "Kidney profile: Urea, Creatinine, Uric acid, BUN, Na, K, Calcium",
      "Liver profile: Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, SGOT, SGPT, Alkaline Phosphatase, GGT, Total Protein, Albumin, Globulin, A/G ratio",
      "2D Echocardiography ",
      "Consultation with Cardiologist",
      "ECG",
      "TMT",
    ],
    price: "6999",
    cancelled: "12000",
  },
  {
    id: 10,
    name: "HVD FEVER PACKAGE",
    url: "hvd-fever",
    image: "/packages/pack8.png",
    description: [
      "Complete Blood Count: Hemoglobin, TLC, DLC (Neutrophils, Lymphocytes, Basophils, Monocytes, Eosinophils), RBC count, PCV, MCV, MCH, MCHC, Platelet count, RDW",
      "Widal Slide",
      "PS for Malaria Parasite",
      "Rapid Malaria Antigen",
      "Typhidot IgM/IgG",
      "NS – 1 Dengue Antigen",
      "Urine R/M: - Colour, Transparency, Specic Gravity, pH, Albumin, Sugar, Pus Cells, RBC, Casts, Crystals, Epithelial Cells, Bacteria, Others",
    ],
    price: "1999",
    cancelled: "3000",
  },
];
